### ISSUE TITLE
build.properties contains 'install.target-dir' property

### ISSUE THREAD

**Issue by prakapenka** [pentaho/pentaho-platform-plugin-reporting#196]
see https://github.com/pentaho/pentaho-platform-plugin-reporting/blob/master/build.properties#L35

While according to build.xml - 

https://github.com/pentaho/pentaho-platform-plugin-reporting/blob/master/build.xml#L12

this value should be determined from 'file="${user.home}/.pentaho-reporting-build-settings.properties' and should not be overridden.

**Comment by pamval** [comment]
@prakapenka we don't usually use the issues in github. Our issue tracker is jira. We should use that to open jiras (either in the reporting project if they affect released versions or in the Backlog project if it affects ongoing work for the next release)

**Comment by EgorZhuk** [comment]
Not up-to-date due to a mavenization
